### ISSUE TITLE
تغییر رنگ برچسب‌ها در این مخزن

### ISSUE THREAD

**Issue by ahangarha** [persian-free-software-ideas/persian-free-software-ideas#11]
<div dir=rtl>

پیشنهاد می‌کنم برچسب‌های مرتبط استفاده شده در این مخزن، از یک خانواده باشند. به عنوان مثلا برچسب‌های زمان مورد نیاز انجام کار، همگی از خانواده رنگ‌های آبی و دارای شدت متفاوت بر حسب زمان مورد نیاز باشند و برچسب سختی، دارای رنگ‌های خانواده قرمز.

**Comment by MCSH** [comment]
خوبه، میتونید 
rgb
بدید؟

پ.ن: شما هم دسترسی دارید در تنظیمات

**Comment by ahangarha** [comment]
<div dir=rtl>

پس انجام می‌دم
