### ISSUE TITLE
مسدود شدن برخی ویدئوهای فارسی در برنامه اندرویدی skytube

### ISSUE THREAD

**Issue by ahangarha** [persian-free-software-ideas/persian-free-software-ideas#16]
<div dir=rtl>

**مشکل چیست؟ لطفا توضیح بدید**
برای ویدئوهای فارسی در برنامه skyTube مسدود می‌شوند

**راه حلی را که دوست دارید ببینید بیان کنید**
احتمالا این مشکل به این بر می‌گردد که زبان این ویدئوها به جای fa مقدار fa_IR دارند. احتمالا این موضوع، یک باگ ساده باشد

**توضیحات تکمیلی**
برنامه [skyTube](http://skytube-app.com/) یک برنامه آزاد برای مشاهده ویدئوهای سایت youTube است. اخیرا در یک به‌روزرسانی، امکان اعمال فیلترهای مختلف برای محدود کردن نتایج جستجو را اضافه کرده است.

![skytube-screenshot-fa-ir-blocking-400px](https://user-images.githubusercontent.com/11241315/46720919-a6222000-cc7e-11e8-8e5d-9bc2d76a3179.png)

**Comment by ahangarha** [comment]
<div dir=rtl>

یک [issue](https://github.com/ram-on/SkyTube/issues/375) در این رابطه در مخزن برنامه ایجاد شده است. علاوه بر این، پرونده معرفی زبان نیز ویرایش شده و یک [درخواست ادغام](https://github.com/ram-on/SkyTube/pull/374) فرستاده شده است.

**Comment by ahangarha** [comment]
@ahangarha ادغام شد. :+1:در انتظار انتشار به‌روزرسانی برنامه جهت تایید رفع مشکل

**Comment by MCSH** [comment]
فکر کنم بهتر باشه این ایشو بسته بشه.

ممنونم ازتون که پیگیری کردین!
